site_name: Deployment Pipeline Reference Architecture
repo_name: "devops/dpra"
repo_url: "https://gitlab.aws.dev/devops/dpra"
edit_uri: "-/edit/main/docs/"
docs_dir: "docs"
copyright: Copyright © Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - toc.integrate
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: 'index.md'
  - Application Pipeline: 'application-pipeline.md'
  - Compute Image Pipeline: 'compute-image-pipeline.md'
  - Account Fleet Management Pipeline: 'account-fleet-management-pipeline.md'
  - Machine Learning Pipeline: 'machine-learning-pipeline.md'
  - Dynamic Configuration Deployment Pipeline: 'dynamic-configuration-deployment-pipeline.md'
  - Download: 'pdf/document.pdf'

markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
        #  format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:mermaid2.fence_mermaid_custom


  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mkdocs_graphviz
plugins:
  - search
  - with-pdf:
      author: AWS Professional Services
      copyright: Copyright © Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
      cover_subtitle: "July 2022"
  - mermaid2:
      version: 9.1.3

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

extra_css:
  - stylesheets/extra.css