site_name: Deployment Pipeline Reference Architecture
repo_name: "devops/dpra"
repo_url: "https://gitlab.aws.dev/devops/dpra"
edit_uri: "-/edit/main/docs/"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Account Fleet Management Pipeline: 'account-fleet-management-pipeline.md'
  - Compute Image Pipeline: 'compute-image-pipeline.md'
  - Application Pipeline: 'application-pipeline.md'
  - Machine Learning Pipeline: 'machine-learning-pipeline.md'
  - Dynamic Configuration Deployment Pipeline: 'dynamic-configuration-deployment-pipeline.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - mermaid2:
      version: 9.1.3
  - with-pdf